/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_UAVAIRQUALITY_PB_H_INCLUDED
#define PB_UAVAIRQUALITY_PB_H_INCLUDED
#include "pb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AirQualityMessageFrame {
    uint32_t SO2_RawData;
    uint32_t NO2_RawData;
    uint32_t CO_RawData;
    uint32_t CO2_RawDate;
} AirQualityMessageFrame;


/* Initializer values for message structs */
#define AirQualityMessageFrame_init_default      {0, 0, 0, 0}
#define AirQualityMessageFrame_init_zero         {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AirQualityMessageFrame_SO2_RawData_tag   1
#define AirQualityMessageFrame_NO2_RawData_tag   2
#define AirQualityMessageFrame_CO_RawData_tag    3
#define AirQualityMessageFrame_CO2_RawDate_tag   4

/* Struct field encoding specification for nanopb */
#define AirQualityMessageFrame_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   SO2_RawData,       1) \
X(a, STATIC,   REQUIRED, UINT32,   NO2_RawData,       2) \
X(a, STATIC,   REQUIRED, UINT32,   CO_RawData,        3) \
X(a, STATIC,   REQUIRED, UINT32,   CO2_RawDate,       4)
#define AirQualityMessageFrame_CALLBACK NULL
#define AirQualityMessageFrame_DEFAULT NULL

extern const pb_msgdesc_t AirQualityMessageFrame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AirQualityMessageFrame_fields &AirQualityMessageFrame_msg

/* Maximum encoded size of messages (where known) */
#define AirQualityMessageFrame_size              24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
